language: python

env:
    - TOX_ENV=py36-django22
    - TOX_ENV=py36-django30
    - TOX_ENV=py37-django22
    - TOX_ENV=py37-django30

install:
    - pip install tox-travis
    - pip install coveralls

script:
    - tox -e $TOX_ENV

sudo: false

after_success:
    coveralls
